interface ImageFormat {
  format: string;
  backgroundColor?: string;
}

interface PNGImageFormat extends ImageFormat {
  format: "png";
  bitDepth?: 8 | 24 | 32;
}

interface JPGImageFormat extends ImageFormat {
  format: "jpg";
  quality?: number;
}

/**
 * The SpriteSheetExporter object is a subclass of the {@link Item | Item object}.
 * @since Adobe Flash Professional CS6
 */
interface SpriteSheetExporter extends Item {
  /**
   * Method; Adds the specified `SymbolItem` or `SymbolInstance` to be used to generate the sprite sheet.
   * @since Adobe Flash Professional CS6
   * @param symbol The `SymbolItem` or `SymbolInstance` to include in the sprite sheet.
   * @param [name] The name of the symbol instance to add to the sprite sheet.
   * @param [beginFrame] The beginning frame of the symbol to include in the sprite sheet.
   * @param [endFrame] The last frame of the symbol to include in the sprite sheet.
   * @usage SpriteSheetExporter.addSymbol(symbol [, name] [, beginFrame] [, endFrame])
   */
  addSymbol(symbol: SymbolItem | SymbolInstance, name?: string, beginFrame?: number, endFrame?: number): void;

  /**
   * Method; Initializes the `SpriteSheetExporter` to create a new sprite sheet.
   * This method is not necessary if you create the exporter from `new`.
   * It is necessary if you reuse the same exporter to make multiple sprite sheets.
   * @since Adobe Flash Professional CS6
   * @returns Nothing.
   */
  beginExport(): void;

  /**
   * Method; Changes the frame range of the symbol that will be used in the sprite sheet.
   * @since Adobe Flash Professional CS6
   * @param symbol A `SymbolItem` or `SymbolInstance` that has already been added to the sprite sheet.
   * @param [beginFrame] Optional. The beginning frame of the symbol to include in the sprite sheet.
   * @param [endFrame] Optional. The last frame of the symbol to include in the sprite sheet.
   * @usage SpriteSheetExporter.changeSymbol( symbol [, beginFrame] [, endFrame] )
   */
  changeSymbol(symbol: SymbolItem | SymbolInstance, beginFrame?: number, endFrame?: number): void;

  /**
   * Method; Exports the sprite sheet into a an image file and a metadata file based on the path parameter.
   * @since Adobe Flash Professional CS6
   * @param path A file path with no extension to be used as the base name of the exported files.
   * @param imageFormat A string or an object that describes the type of image format to generate.
   *
   * - String: Valid values are either "png" or "jpg", the exporter use whatever values where last used.
   * - Object: If you pass an object, it needs at least a string property "format" which is either "png" or "jpg".
   * Optionally the object may include "backgroundColor", which is a valid color value (alpha may be included);
   * "quality" (jpg only), which is an integer from 1 to 100;
   * and "bitDepth" (png only) which can be 8, 24 or 32.
   * @param [writeMetaData] Optional. Whether or not to write the metadata file with the image file. The default value is true.
   * @returns The metadata generated by the sprite sheet plugin or nothing if an error occurred.
   * @usage SpriteSheetExporter.exportSpriteSheet(path, imageFormat [, writeMetaData])
   * @example
   *
   * The following examples exports to a PNG with transparency:
   *
   * ```javascript
   * var sse = new SpriteSheetExporter();
   * sse.exportSpriteSheet("file:///C|/xxx/sprite-sheet/test", {
   *   format: "png",
   *   bitDepth: 32,
   *   backgroundColor: "#00000000"
   * });
   * ```
   */
  exportSpriteSheet(path: string, imageFormat: "png" | "jpg" | PNGImageFormat | JPGImageFormat, writeMetaData?: boolean): string;

  /**
   * Method; Removes the specified bitmap or bitmapItem from the sprite sheet object.
   * @since Adobe Flash Professional CS6
   * @param bitmap The `BitmapItem` or `BitmapInstance` to remove from the sprite sheet.
   * @returns Nothing.
   */
  removeBitmap(bitmap: BitmapItem | BitmapInstance): void;

  /**
   * Method; Removes the specified `SymbolItem` or `SymbolInstance` from the sprite sheet.
   * @since Adobe Flash Professional CS6
   * @param symbol The `SymbolItem` or `SymbolInstance` to remove from the sprite sheet.
   */
  removeSymbol(symbol: SymbolItem | SymbolInstance): void;

  /**
   * Property; A string indicating which algorithm to use to pack the sprite sheet.
   * Valid values are "basic" (the default), and "maxRects".
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * exporter.algorithm = "maxRects";
   * ```
   */
  algorithm: "basic" | "maxRects";

  /**
   * Property; A boolean value indicating whether the symbol frames can be rotated when packed into the sprite sheet.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * exporter.allowRotate = true;
   * ```
   */
  allowRotate: boolean;

  /**
   * Property; A boolean value indicating whether the symbol frames can be trimmed of any extra whitespace when packed into the sprite sheet.
   * The default value is true.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * exporter.allowTrimming = false;
   * ```
   */
  allowTrimming: boolean;

  /**
   * Read-only property; The name of the application that is generating the sprite sheet.
   * This property is provided for use by any future sprite sheet generator plugins that may be created for Flash Pro.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * alert(exporter.app);
   * // "Flash Pro CS6"
   * ```
   */
  readonly app: string;

  /**
   * Property; A boolean value indicating whether the sprite sheet exporter should calculate the overall size
   * of the sprite sheet on its own.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * exporter.autoSize = false;
   * ```
   */
  autoSize: boolean;

  /**
   * Property; An integer indicating the number of pixels of padding to add around each sprite in the sprite sheet.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * exporter.borderPadding = 5;
   * ```
   */
  borderPadding: number;

  /**
   * Read-only property; A boolean value indicating whether the framework specified
   * by the `SpriteSheetExporter.layoutFormat` property supports border padding.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * alert(exporter.canBorderPad);
   * ```
   */
  readonly canBorderPad: boolean;

  /**
   * Read-only property; A boolean value indicating whether the framework specified
   * by the `SpriteSheetExporter.layoutFormat` property may rotate symbol frames when adding them to the sprite sheet.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * alert(exporter.canRotate);
   * ```
   */
  readonly canRotate: boolean;

  /**
   * Read-only property; A boolean value indicating whether the framework specified
   * by the `SpriteSheetExporter.layoutFormat` property supports shape padding.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * alert(exporter.canShapePad);
   * ```
   */
  readonly canShapePad: boolean;

  /**
   * Read-only property; A boolean value indicating whether the framework specified
   * by the `SpriteSheetExporter.layoutFormat` property supports stacking duplicate symbol frames within the sprite sheet.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * alert(exporter.canStackDuplicateFrames);
   * ```
   */
  readonly canStackDuplicateFrames: boolean;

  /**
   * Read-only property; A boolean value indicating whether the framework specified
   * by the `SpriteSheetExporter.layoutFormat` property supports trimming extra whitespace from symbol frames when adding them to the sprite sheet.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * alert(exporter.canTrim);
   * ```
   */
  readonly canTrim: boolean;

  /**
   * Read-only property; A string value indicating the format of the sprite sheet image file.
   * Possible values include "RGBA8888", "RGB888x", and "RGB8".
   * This property is provided for use by sprite sheet generator plugins.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * alert(exporter.format); // "RGBA8888"
   * ```
   */
  readonly format: "RGBA8888" | "RGB888x" | "RGB8";

  /**
   * Read-only property; A string value indicating the name of the sprite sheet image file.
   * This property is provided for use by sprite sheet generator plugins.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * alert(exporter.image);
   * ```
   */
  readonly image: string;

  /**
   * Property; A string value indicating the format of the sprite sheet metadata.
   * Valid values depend on the contents of the Sprite Sheet Plugin directory.
   * "JSON" (JavaScript Object Notation) is one possible value.
   *
   * Your script passes the layout format's ID string to match one of the .jsfl files defined for the Sprite Sheet plugin
   * (located in the *flashroot*\/Common/Configuration/Sprite Sheet Plugins folder).
   *
   * These files have the naming convention *layoutformat*.plugin.jsfl and you pass a string set to *layoutformat*.
   * For example, you would set layoutFormat equal to "Starling", "cocos2D v2", or "cocos2D v3".
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * exporter.layoutFormat = "JSON";
   * ```
   */
  layoutFormat: string;

  /**
   * Controls the maximum height of the generated sprite sheet when `autoSize = true`,
   * clipped to a maximum value of 8192.
   * @since Adobe Flash Professional CC
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * exporter.autoSize = true;
   * exporter.maxSheetHeight = 512;
   * ```
   */
  maxSheetHeight: number;

  /**
   * Controls the maximum width of the generated sprite sheet when `autoSize = true`,
   * clipped to a maximum value of 8192.
   * @since Adobe Flash Professional CC
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * exporter.autoSize = true;
   * exporter.maxSheetWidth = 512;
   * ```
   */
  maxSheetWidth: number;

  /**
   * Read-only property; A boolean value indicating whether all the exported symbol frames cannot fit
   * within the currently specified size of the sprite sheet.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * if (exporter.overflowed) exporter.sheetWidth = 1024;
   * ```
   */
  readonly overflowed: boolean;

  /**
   * Property; An integer value indicating how many pixels of padding should be added to each exported symbol frame when adding it to the sprite sheet.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * exporter.shapePadding = 10;
   * ```
   */
  shapePadding: number;

  /**
   * Property; An integer value specifying the height of the sprite sheet.
   * This value is read-only if `SpriteSheetExporter.autoSize` is set to true.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * exporter.sheetHeight = 512;
   * ```
   */
  sheetHeight: number;

  /**
   * Property; An integer value specifying the width of the sprite sheet.
   * This value is read-only if `SpriteSheetExporter.autoSize` is set to true.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * exporter.sheetwidth = 512;
   * ```
   */
  sheetWidth: number;

  /**
   * Property; A boolean value specifying whether the sprite sheet can stack duplicate symbol frames when adding them to the sprite sheet.
   * The default is true.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * exporter.stackDuplicateFrames = true;
   * ```
   */
  stackDuplicateFrames: boolean;

  /**
   * Read-only property; A stinr gindicating the version number of the Flash Pro application.
   * This property is provided for use by sprite sheet plugins.
   * @since Adobe Flash Professional CS6
   * @example
   *
   * ```javascript
   * var exporter = new SpriteSheetExporter();
   * alert(exporter.verion); // "12.0.0.416"
   * ```
   */
  readonly version: string;
}

interface SpriteSheetExporterConstructor {
  new(): SpriteSheetExporter;
}

declare var SpriteSheetExporter: SpriteSheetExporterConstructor;
