/**
 * The Timeline object represents the Animate timeline,
 * which can be accessed for the current document by using `fl.getDocumentDOM().getTimeline()`.
 *
 * This method returns the timeline of the current scene or symbol that is being edited.
 *
 * When you work with scenes, each scene's timeline has an index value,
 * and can be accessed for the current document by `fl.getDocumentDOM().timelines[i]`.
 *
 * When you work with frames by using the methods and properties of the Timeline object,
 * remember that the frame value is a zero-based index (not the actual frame number in the sequence of frames in the timeline).
 * That is, the first frame has a frame index of 0.
 * @since Macromedia Flash MX Basic/Professional 2004
 */
interface Timeline {
  /**
   * Method; Adds a motion guide layer above the current layer and attaches the current layer to the newly added guide layer,
   * converting the current layer to a layer of type "Guided".
   *
   * This method functions only on a layer of type **Normal**.
   * It has no effect on a layer whose type is "Folder", "Mask", "Masked", "Guide", or "Guided".
   * @since Macromedia Flash MX Basic/Professional 2004
   * @returns An integer that represents the zero-based index of the newly added guide layer.
   * If the current layer type is not of type "Normal", Animate returns -1.
   * @example
   *
   * The following example adds a motion guide layer above the current layer, and converts the current layer to Guided:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().addMotionGuide();
   * ```
   */
  addMotionGuide(): number;

  /**
   * Method; Adds a new layer to the document and makes it the current layer.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [name] The name for the new layer.
   * If omitted, a new default layer name is assigned to the new layer
   * ("Layer *n*", where *n* is the total number of layers created and deleted for that particular instance of the file).
   * @param [layerType] The type of layer to add. If omitted, a "normal" type layer is created.
   *
   * Acceptable values are "normal", "guide", "guided", "mask", "masked", and "folder".
   * @param [addAbove] A boolean value that, if set to true (the default),
   * causes Animate to add the new layer above the current layer;
   * `false` causes Animate to add the layer below the current layer.
   * @returns An integer value of the zero-based index of the newly added layer.
   * @example
   *
   * The following example adds a new layer to the timeline with a default name generated by Animate:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().addNewLayer();
   * ```
   *
   * The following example adds a new folder layer on top of the current layer and names it "Folder1":
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().addNewLayer("Folder1", "folder", true);
   * ```
   */
  addNewLayer(name?: string, layerType?: "normal" | "guide" | "guided" | "mask" | "masked" | "folder", addAbove?: boolean): number;

  /**
   * Method; Deletes all the contents from a frame or range of frames on the current layer.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [startFrameIndex] A zero-based integer index indicating where to start clearing frames.
   * If omitted, the current selection is used.
   * @param [endFrameIndex] A zero-based integer index indicating the end (exclusive) of the frames to clear.
   * If omitted, only the frame at **`startFrameIndex`** is cleared.
   * @returns Nothing.
   * @example
   *
   * The following example clears the frames from Frame 6 up to, but not including,
   * Frame 11 (remember that index values are different from frame number values):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().clearFrames(5, 10);
   * ```
   *
   * The following example clears Frame 15:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().clearFrames(14);
   * ```
   */
  clearFrames(startFrameIndex?: number, endFrameIndex?: number): void;

  /**
   * Method; Converts a keyframe to a regular frame and deletes its contents on the current layer.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [startFrameIndex] A zero-based integer index that specifies where to start clearing keyframes.
   * If omitted, the current selection is used.
   * @param [endFrameIndex] A zero-based integer index marking the end of the range of frames to clear (not inclusive).
   * If omitted, only the frame at **`startFrameIndex`** is cleared.
   * @returns Nothing.
   * @example
   *
   * The following example clears the keyframes from Frame 5 up to, but not including,
   * Frame 10 (remember that index values are different from frame number values):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().clearKeyframes(4, 9);
   * ```
   *
   * The following example clears the keyframe at Frame 15 and converts it to a regular frame:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().clearKeyframes(14);
   * ```
   */
  clearKeyframes(startFrameIndex?: number, endFrameIndex?: number): void;

  /**
   * Method; Converts frames to blank keyframes on the current layer.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [startFrameIndex] A zero-based integer index specifying the starting frame to convert to blank keyframes.
   * If omitted, the method uses the currently selected frames.
   * @param [endFrameIndex] A zero-based integer index specifying the frame where the conversion stops (not inclusive).
   * If omitted, only the frame at **`startFrameIndex`** is converted.
   * @returns Nothing.
   * @example
   *
   * The following example converts Frame 2 up to, but not including,
   * Frame 10 to blank keyframes (remember that index values are different from frame number values):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().convertToBlankKeyframes(1, 9);
   * ```
   *
   * The following example converts Frame 5 to a blank keyframe:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().convertToBlankKeyframes(4);
   * ```
   */
  convertToBlankKeyframes(startFrameIndex?: number, endFrameIndex?: number): void;

  /**
   * Method; Converts a range of frames to keyframes
   * (or converts the selection if no frames are specified) on the current layer.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [startFrameIndex] A zero-based integer index specifying the first frame to convert to keyframes.
   * If omitted, the method converts the currently selected frames.
   * @param [endFrameIndex] A zero-based integer index specifying the frame where conversion to keyframes stops (exclusive).
   * If omitted, only the frame at **`startFrameIndex`** is converted.
   * @returns Nothing.
   * @example
   *
   * The following example converts the selected frames to keyframes:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().convertToKeyframes();
   * ```
   *
   * The following example converts to keyframes the frames from Frame 2 up to, but not including,
   * Frame 10 (remember that index values are different from frame number values):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().convertToKeyframes(1, 9);
   * ```
   *
   * The following example converts Frame 5 to a keyframe:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().convertToKeyframes(4);
   * ```
   */
  convertToKeyframes(startFrameIndex?: number, endFrameIndex?: number): void;

  /**
   * Method; Copies a range of frames on the current layer to the clipboard.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [startFrameIndex] A zero-based integer index indicating the first frame to copy.
   * If omitted, the method copies the currently selected frames.
   * @param [endFrameIndex] A zero-based integer index indicating the frame to stop copying at (not inclusive).
   * If omitted, only the frame at **`startFrameIndex`** is copied.
   * @returns Nothing.
   * @example
   *
   * The following example copies the selected frames to the clipboard:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().copyFrames();
   * ```
   *
   * The following example copies Frame 2 up to, but not including,
   * Frame 10, to the clipboard (remember that index values are different from frame number values):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().copyFrames(1, 9);
   * ```
   *
   * The following example copies Frame 5 to the clipboard:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().copyFrames(4);
   * ```
   */
  copyFrames(startFrameIndex?: number, endFrameIndex?: number): void;

  /**
   * Method; Copies the layers that are currently selected in the Timeline,
   * or the layers in the specified range.
   *
   * Optional arguments can be provided in order to specify a layer or range of layers to copy.
   * @since Adobe Flash Professional CS5.5
   * @param [startLayerIndex] A zero-based integer index that specifies the first layer to copy.
   * If omitted, the method copies the currently selected layers.
   * @param [endLayerIndex] A zero-based integer index indicating the last layer to copy, inclusive.
   * If omitted, only the layer at **`startLayerIndex`** is copied.
   * @returns Nothing.
   * @example
   *
   * The following example copies the layers from index 2 to index 7 in the Timeline:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().copyLayers(2, 7);
   * ```
   * @see
   *
   * - {@link Timeline.cutLayers | Timeline.cutLayers()}
   * - {@link Timeline.pasteLayers | Timeline.pasteLayers()}
   * - {@link Timeline.duplicateLayers | Timeline.duplicateLayers()}
   */
  copyLayers(startLayerIndex?: number, endLayerIndex?: number): void;

  /**
   * Method; Copies motion on selected frames, either from a motion tween or from frame-by-frame animation.
   * You can then use {@link Timeline.pasteMotion | Timeline.pasteMotion()} to apply the motion to other frames.
   *
   * To copy motion as text (code) that you can paste into a script,
   * see {@link Timeline.copyMotionAsAS3 | Timeline.copyMotionAsAS3()}.
   * @since Adobe Flash Professional CS3
   * @returns Nothing.
   * @example
   *
   * The following example copies the motion from the selected frame or frames:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().copyMotion();
   * ```
   * @see
   *
   * - {@link Timeline.copyMotionAsAS3 | Timeline.copyMotionAsAS3()}
   * - {@link Timeline.pasteMotion | Timeline.pasteMotion()}
   */
  copyMotion(): void;

  /**
   * Method; Copies motion on selected frames, either from a motion tween or from frame-by-frame animation,
   * to the clipboard as ActionScript 3.0 code. You can then paste this code into a script.
   * To copy motion in a format that you can apply to other frames,
   * see {@link Timeline.copyMotion | Timeline.copyMotion()}.
   * @since Adobe Flash Professional CS3
   * @returns Nothing.
   * @example
   *
   * The following example copies the motion from the selected frame
   * or frames to the clipboard as ActionScript 3.0 code:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().copyMotionAsAS3();
   * ```
   * @see {@link Timeline.copyMotion | Timeline.copyMotion()}
   */
  copyMotionAsAS3(): void;

  /**
   * Method; Creates a new motion object.
   *
   * The parameters are optional, and if specified set the timeline selection to the indicated frames prior to creating the motion object.
   * @since Adobe Flash Professional CS5
   * @param [startFrame] A zero-based integer index that specifies the starting frame for the motion object.
   * If omitted, the current selection or playhead frame is used.
   * @param [endFrame] A zero-based integer index that specifies the frame where the motion object ends (not inclusive).
   * If omitted, it defaults to the value of **`startFrame`**.
   * @returns Nothing.
   * @example
   *
   * The following example creates a motion objects at the current playhead position on the top layer:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().currentLayer = 0;
   * fl.getDocumentDOM().getTimeline().createMotionObject();
   * ```
   *
   * The following example creates a motion object starting at Frame 5, and extending up to,
   * but not including, Frame 15 of the top layer in the current scene:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().currentLayer = 0;
   * fl.getDocumentDOM().getTimeline().createMotionObject(5, 15);
   * ```
   */
  createMotionObject(startFrame?: number, endFrame?: number): void;

  /**
   * Method; Sets the {@link Frame.tweenType} property to motion for each selected keyframe on the current layer,
   * and converts each frame's contents to a single symbol instance if necessary.
   * This property is the equivalent to the `Create Motion Tween` menu item in the Animate authoring tool.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [startFrameIndex] A zero-based integer index indicating the starting frame for the motion tween.
   * If omitted, the current selection is used.
   * @param [endFrameIndex] A zero-based integer index indicating the frame where the motion tween ends (exclusive).
   * If omitted, it defaults to the value of **`startFrameIndex`**.
   * @returns Nothing.
   * @example
   *
   * The following example converts the shape in the first frame up to, but not including,
   * Frame 10 to a graphic symbol instance and sets the {@link Frame.tweenType} to motion
   * (remember that index values are different from frame number values):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().createMotionTween(0, 9);
   * ```
   */
  createMotionTween(startFrameIndex?: number, endFrameIndex?: number): void;

  /**
   * Method; cuts a range of frames on the current layer from the timeline and saves them to the clipboard.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [startFrameIndex] A zero-based integer index that specifies the first frame to cut.
   * If omitted, the current selection is used.
   * @param [endFrameIndex] A zero-based index indicating the frame where cutting stops (not included in the cut).
   * If omitted, only the frame at **`startFrameIndex`** is cut.
   * @returns Nothing.
   * @example
   *
   * The following example cuts the selected frames from the timeline and saves them to the clipboard:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().cutFrames();
   * ```
   *
   * The following example cuts Frame 2 up to, but not including,
   * Frame 10 from the timeline and saves them to the clipboard
   * (remember that index values are different from frame number values):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().cutFrames(1, 9);
   * ```
   *
   * The following example cuts Frame 5 from the timeline and saves it to the clipboard:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().cutFrames(4);
   * ```
   */
  cutFrames(startFrameIndex?: number, endFrameIndex?: number): void;

  /**
   * Method; Cuts the layers that are currently selected in the Timeline, or the layers in the specified range.
   *
   * Optional arguments can be provided in order to specify a layer or range of layers to cut.
   * @since Adobe Flash Professional CS5.5
   * @param [startLayerIndex] A zero-based integer index that specifies the first layer to cut.
   * If omitted, the method uses the currently selected layers.
   * @param [endLayerIndex] A zero-based integer index specifying the last layer to cut, inclusive.
   * If omitted, only the **`startLayerIndex`** layer is cut.
   * @returns Nothing.
   * @example
   *
   * The following example cuts the layers from index 2 to index 7 in the Timeline:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().cutLayers(2, 7);
   * ```
   * @see
   *
   * - {@link Timeline.copyLayers | Timeline.copyLayers()}
   * - {@link Timeline.pasteLayers | Timeline.pasteLayers()}
   * - {@link Timeline.duplicateLayers | Timeline.duplicateLayers()}
   */
  cutLayers(startLayerIndex?: number, endLayerIndex?: number): void;

  /**
   * Method; Deletes a layer.
   *
   * If the layer is a folder, all layers within the folder are deleted.
   * If you do not specify the layer index, Animate deletes the currently selected layers.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [index] A zero-based integer specifying which layer to delete.
   * If omitted, the currently selected layers are deleted.
   *
   * If only one layer exists, the method does nothing.
   * @returns Nothing.
   * @example
   *
   * The following example deletes the second layer from the top:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().deleteLayer(1);
   * ```
   *
   * The following example deletes the currently selected layers:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().deleteLayer();
   * ```
   */
  deleteLayer(index?: number): void;

  /**
   * Method; Duplicates the layers that are currently selected in the Timeline, or the layers in the specified range.
   *
   * Optional arguments can be provided in order to specify a layer or range of layers to duplicate.
   * @since Adobe Flash Professional CS5.5
   * @param [startLayerIndex] A zero-based index indicating the first layer to duplicate.
   * If omitted, the currently selected layers are duplicated.
   * @param [endLayerIndex] A zero-based integer indicating the last layer to duplicate.
   * The duplication includes all layers from **`startLayerIndex`** to **`endLayerIndex`**, inclusive.
   * If omitted, only the layer at **`startLayerIndex`** is duplicated.
   * @returns Nothing.
   * @example
   *
   * The following example duplicates the layer currently selected in the Timeline:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().duplicateLayers();
   * ```
   *
   * The following example duplicates the layers from index 2 to index 7 above layer index 2:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().duplicatedLayers(2, 7);
   * ```
   * @see
   *
   * - {@link Timeline.copyLayers | Timeline.copyLayers()}
   * - {@link Timeline.cutLayers | Timeline.cutLayers()}
   * - {@link Timeline.pasteLayers | Timeline.pasteLayers()}
   */
  duplicateLayers(startLayerIndex?: number, endLayerIndex?: number): void;

  /**
   * Method; Expands or collapses the specified folder or folders.
   *
   * If you do not specify a layer, this method operates on the current layer.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param expand A boolean value that, if set to `true`, causes the method to expand the folder;
   * `false` causes the method to collapse the folder.
   * @param [recurseNestedParents] A boolean value that,
   * if set to `true`, causes all the layers within the specified folder to be opened or closed,
   * based on the **`expand`** parameter.
   * @param [index] A zero-based index of the folder to expand or collapse.
   * Use -1 to apply to all layers (you also must set **`recurseNestedParents`** to `true`).
   * This property is equivalent to the `Expand All/Collapse All` menu items in the Animate authoring tool.
   * @returns Nothing.
   * @example
   *
   * The following examples use this folder structure:
   *
   * ```
   * Folder 1
   * ├─ layer 7
   * ├─ Folder 2
   *    └─ Layer 5
   * ```
   *
   * The following example expands Folder 1 only:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().currentLayer = 1;
   * fl.getDocumentDOM().getTimeline().expandFolder(true);
   * ```
   *
   * The following example expands Folder 1 only (assuming that Folder 2 collapsed when Folder 1 last collapsed;
   * otherwise, Folder 2 appears expanded):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().expandFolder(true, false, 0);
   * ```
   *
   * The following example collapses all folders in the current timeline:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().expandFolder(false, true, -1);
   * ```
   */
  expandFolder(expand: boolean, recurseNestedParents?: boolean, index?: number): void;

  /**
   * Method; Finds an array of indexes for the layers with the given name.
   *
   * The layer index is flat, so folders are considered part of the main index.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param name The name of the layer to find.
   * @returns An array of index values for the specified layer.
   *
   * If the specified layer is not found, Animate returns `undefined`.
   * @example
   *
   * The following example shows the index values of all layers named "Layer 7" in the Output panel:
   *
   * ```javascript
   * var layerIndex = fl.getDocumentDOM().getTimeline().findLayerIndex("Layer 7");
   * fl.trace(layerIndex);
   * ```
   *
   * The following example illustrates how to pass the values returned from this method back to
   * {@link Timeline.setSelectedLayers | Timeline.setSelectedLayers()}:
   *
   * ```javascript
   * var layerIndex = fl.getDocumentDOM().getTimeline().findLayerIndex("Layer 1");
   * fl.getDocumentDOM().getTimeline().setSelectedLayers(layerIndexAnimate[0], true);
   * ```
   */
  findLayerIndex(name: string): number[] | undefined;

  /**
   * Method; Returns the bounding rectangle for all elements on all layers on the Timeline, for a given frame.
   * @since Adobe Animate CC 2016
   * @param [frame] The number of the frame for which you want the bounds.
   * Defaults to 1, which is the first frame.
   * @param [includeHiddenLayers] Indicates whether to include element bounds from hidden layers.
   * Defaults to the SWF publish setting value for "include hidden layers".
   * @returns The bounding rectangle for all elements on all layers on the Timeline, for the specified frame.
   * @example
   *
   * The following example illustrates the use of this method:
   *
   * ```javascript
   * var doc = fl.getDocumentDOM();
   * var tl = doc.getTimeline();
   * for (var f = 1; f <= 20; f++) {
   *   var rect = tl.getBounds(f, true);
   *   if (rect != 0) {
   *     var width = rect.right - rect.left;
   *     var height = rect.bottom - rect.top;
   *     fl.trace("" + rect.left + "," + rect.top + "," + width + "," + height);
   *   }
   * }
   * ```
   */
  getBounds(frame?: number, includeHiddenLayers?: boolean): RectangleBounds;

  /**
   * Method; retrieves the specified property's value for the selected frames.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param property The name of the property for which to get the value.
   * @param [startFrameIndex] A zero-based integer index specifying the starting frame
   * for which to get the property value.
   * If omitted, the current selection is used.
   * @param [endFrameIndex] A zero-based integer index specifying the end frame (exclusive) of the range.
   * If omitted, it defaults to the value of **`startFrameIndex`**.
   * @returns A value for the specified property,
   * or `undefined` if all the selected frames do not have the same property value.
   * @example
   *
   * The following example retrieves the name of the first frame in the current document's top layer
   * and displays the name in the Output panel:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().currentLayer = 0;
   * fl.getDocumentDOM().getTimeline().setSelectedFrames(0, 0, true);
   * var frameName = fl.getDocumentDOM().getTimeline().getFrameProperty("name");
   * fl.trace(frameName);
   * ```
   */
  getFrameProperty(property: string, startFrameIndex?: number, endFrameIndex?: number): any | undefined;

  /**
   * Method; Returns an XML string that represents the current positions of the horizontal and vertical guide lines
   * for a timeline (`View > Guides > Show Guides`).
   *
   * To apply these guide lines to a timeline, use {@link Timeline.setGuidelines | Timeline.setGuidelines()}.
   * @since Adobe Flash Professional CS4
   * @returns An XML string.
   * @example
   *
   * Assuming that you have some guide lines on the first timeline,
   * the following example displays them as an XML string in the Output panel:
   *
   * ```javascript
   * var currentTimeline = fl.getDocumentDOM().timelines[0];
   * fl.trace(currentTimeline.getGuidelines());
   * ```
   */
  getGuidelines(): string;

  /**
   * Method; Retrieves the specified property's value for the selected layers.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param property The name of the property whose value you want to retrieve.
   * @returns The value of the specified property. Animate looks at the layer's properties to determine the type.
   * If all the specified layers don't have the same property value, Animate returns `undefined`.
   * @example
   *
   * The following example retrieves the name of the top layer in the current document
   * and displays it in the Output panel:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().currentLayer = 0;
   * var layerName = fl.getDocumentDOM().getTimeline().getLayerProperty("name");
   * fl.trace(layerName);
   * ```
   */
  getLayerProperty(property: string): any | undefined;

  /**
   * Method; Retrieves the currently selected frames in an array.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @returns An array containing 3 × *n* integers, where *n* is the number of selected regions.
   * The first integer in each group is the layer index,
   * the second integer is the start frame of the beginning of the selection,
   * and the third integer specifies the ending frame of that selection range.
   *
   * The ending frame is not included in the selection.
   * @example
   *
   * With the top layer being the current layer,
   * the following example displays `0,5,10,0,20,25` in the Output panel:
   *
   * ```javascript
   * var timeline = fl.getDocumentDOM().getTimeline();
   * timeline.setSelectedFrames(5, 10);
   * timeline.setSelectedFrames(20, 25, false);
   * var theSelectedFrames = timeline.getSelectedFrames();
   * fl.trace(theSelectedFrames);
   * ```
   * @see {@link Timeline.setSelectedFrames | Timeline.setSelectedFrames()}
   */
  getSelectedFrames(): number[];

  /**
   * Method; Gets the zero-based index values of the currently selected layers.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @returns An array of the zero-based index values of the selected layers.
   * @example
   *
   * The following example displays `1,0` in the Output panel:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().setSelectedLayers(0);
   * fl.getDocumentDOM().getTimeline().setSelectedLayers(1, false);
   * var layerArray = fl.getDocumentDOM().getTimeline().getSelectedLayers();
   * fl.trace(layerArray);
   * ```
   * @see {@link Timeline.setSelectedLayers | Timeline.setSelectedLayers()}
   */
  getSelectedLayers(): number[];

  /**
   * Method; Inserts a blank keyframe at the specified frame index
   *
   * If the index is not specified, the method inserts the blank keyframe by using the playhead/selection.
   * See also {@link Timeline.insertKeyframe | Timeline.insertKeyframe()}.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [frameNumIndex] A zero-based integer indicating the frame index where the blank keyframe will be inserted.
   * If omitted, the current playhead frame is used.
   * @returns Nothing.
   * @example
   *
   * The following example inserts a blank keyframe at Frame 20
   * (remember that index values are different from frame number values):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().insertBlankKeyframe(19);
   * ```
   *
   * The following example inserts a blank keyframe at the currently selected frame
   * (or playhead location if no frame is selected):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().insertBlankKeyframe();
   * ```
   */
  insertBlankKeyframe(frameNumIndex?: number): void;

  /**
   * Method; Inserts the specified number of frames at the specified index.
   *
   * If no parameters are specified, this method works as follows:
   *
   * - If one or more frames are selected,
   * the method inserts the selected number of frames at the location of the first selected frame in the current layer.
   * That is, if frames 6 through 10 are selected (a total of five frames),
   * the method adds five frames at Frame 6 in the layer containing the selected frames.
   * - If no frames are selected, the method inserts one frame at the current frame on all layers.
   * If parameters are specified, the method works as follows:
   *   - If only **`numFrames`** is specified,
   * inserts the specified number of frames at the current frame on the current layer.
   *   - If **`numFrames`** is specified and **`allLayers`** is `true`,
   * inserts the specified number of frames at the current frame on all layers.
   *   - If all three parameters are specified,
   * inserts the specified number of frames at the specified index (*frameIndex*);
   * the value passed for **`allLayers`** determines if the frames are added only to the current layer or to all layers.
   *
   * If the specified or selected frame is a regular frame, the frame is inserted at that frame.
   * For example, if you have a span of 10 frames numbered 1-10 and you select Frame 5
   * (or pass a value of 4 for *frameIndex*),
   * this method adds a frame at Frame 5, and the length of the frame span becomes 11 frames.
   * If Frame 5 is selected and it is a keyframe,
   * this method inserts a frame at Frame 6 regardless of whether the frame next to it is also a keyframe.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [numFrames] The number of frames to insert.
   * If omitted, the method determines the number of frames based on the current selection.
   * @param [allLayers] A boolean value that,
   * if set to `true`, causes the method to insert the specified number of frames in the **`numFrames`** parameter
   * into all layers; if set to `false` (the default), the method inserts frames into the current layer.
   * @param [frameNumIndex] A zero-based integer specifying the frame index where frames will be inserted.
   * if omitted, frames are inserted at the current frame.
   * @returns Nothing.
   * @example
   *
   * The following example inserts a frame (or frames, depending on the selection)
   * at the current selection in the current layer:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().insertFrames();
   * ```
   *
   * The following example inserts five frames at the current frame in all layers:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().insertFrames(5);
   * ```
   *
   * ***Note:** If you have multiple layers with frames in them,
   * and you select a frame in one layer when using the previous command,
   * Flash inserts the frames in the selected layer only.
   * If you have multiple layers with no frames selected in them,
   * Flash inserts the frames in all layers.*
   *
   * The following example inserts three frames in the current layer only:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().insertFrames(3, false);
   * ```
   *
   * The following example inserts four frames in all layers, starting
   * from the first frame:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().insertFrames(4, true, 0);
   * ```
   */
  insertFrames(numFrames?: number, allLayers?: boolean, frameNumIndex?: number): void;

  /**
   * Method; Inserts a keyframe at the specified frame.
   *
   * If you omit the parameter, the method inserts a keyframe using the playhead or selection location.
   *
   * This method works the same as {@link Timeline.insertBlankKeyframe | Timeline.insertBlankKeyframe()}
   * except that the inserted keyframe contains the contents of the frame it converted (that is, it's not blank).
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [frameNumIndex] A zero-based integer specifying the frame index in the current layer
   * where the keyframe will be inserted.
   * If omitted, the current playhead or selected frame is used.
   * @returns Nothing.
   * @example
   *
   * The following example inserts a keyframe at the playhead or selected location:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().insertKeyframe();
   * ```
   *
   * The following example inserts a keyframe at Frame 10 of the second layer
   * (remember that index values are different from frame or layer number values):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().currentLayer = 1;
   * fl.getDocumentDOM().getTimeline().insertKeyframe(9);
   * ```
   */
  insertKeyframe(frameNumIndex?: number): void;

  /**
   * Method; Merge the layers within specified range of indexes.
   * @since Adobe Animate 2020
   * @param startLayerNum Integer that specifies the starting layer index.
   * @param endLayerNum Integer that specifies the ending layer index.
   * @returns Layer object of the merged layer.
   * @example
   *
   * The following example merge layers from index 0 to 3.
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().mergeLayers(0, 3);
   * ```
   */
  mergeLayers(startLayerNum: number, endLayerNum: number): Layer;

  /**
   * Method; Pastes the range of frames from the clipboard into the specified frames.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [startFrameIndex] A zero-based integer index indicating where to start pasting frames.
   * If omitted, the current selection is used.
   * @param [endFrameIndex] A zero-based integer index indicating the frame where pasting stops (not included).
   * If omitted, pasting ends at the **`startFrameIndex`**.
   * @returns Nothing.
   * @example
   *
   * The following example pastes the frames on the clipboard to the currently selected frame or playhead location:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().pasteFrames();
   * ```
   *
   * The following example pastes the frames on the clipboard at Frame 2 up to, but not including,
   * Frame 10 (remember that index values are different from frame number values):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().pasteFrames(1, 9);
   * ```
   *
   * The following example pastes the frames on the clipboard starting at Frame 5:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().pasteFrames(4);
   * ```
   */
  pasteFrames(startFrameIndex?: number, endFrameIndex?: number): void;

  /**
   * Method; Paste layers that have been previously cut or copied above the currently selected layer,
   * or above the specified layer index.
   *
   * If the specified layer is a folder layer, the layers are pasted into the folder.
   * Returns the lowest layer index of the layers that were pasted.
   *
   * This action does not affect the system clipboard.
   * @since Adobe Flash Professional CS5.5
   * @param [layerIndex] A zero-based integer specifying the layer above which the clipboard layers are pasted.
   * If omitted, the current selection is used.
   * @returns Integer indicating the lowest layer index of the layers that were pasted.
   * @example
   *
   * The following example pastes the layers from the layer clipboard above the currently selected layer in the Timeline:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().pasteLayers();
   * ```
   *
   * The following example pastes the layers from the layer clipboard above layer index 2:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().pasteLayers(2);
   * ```
   * @see
   *
   * - {@link Timeline.cutLayers | Timeline.cutLayers()}
   * - {@link Timeline.copyLayers | Timeline.copyLayers()}
   * - {@link Timeline.duplicateLayers | Timeline.duplicateLayers()}
   */
  pasteLayers(layerIndex?: number): number;

  /**
   * Method; Pastes the range of motion frames retrieved
   * by {@link Timeline.copyMotion | Timeline.copyMotion()} to the Timeline.
   *
   * If necessary, existing frames are displaced (moved to the right) to make room for the frames being pasted.
   * @since Adobe Flash Professional CS3
   * @returns Nothing.
   * @example
   *
   * The following example pastes the motion on the clipboard to the currently selected frame or playhead location,
   * displacing that frame to the right of the pasted frames:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().pasteMotion();
   * ```
   * @see {@link Timeline.copyMotion | Timeline.copyMotion()}
   */
  pasteMotion(): void;

  /**
   * Method; Pastes motion on selected frames.
   * Applies only to a copied classic tween, not a motion tween.
   *
   * Displays a dialog box whose options let the user choose which parts of a classic tween to apply when pasting:
   * X position, Y position, Horizontal scale, Vertical scale, Rotation and skew, Color, Filters, Blend mode.
   * @since Adobe Flash Professional CS3
   * @returns Nothing.
   * @example
   *
   * The following example displays the dialog, then pastes the classic tween to the selected frames:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().pasteMotionSpecial();
   * ```
   * @see {@link Timeline.pasteMotion | Timeline.pasteMotion()}
   */
  pasteMotionSpecial(): void;

  /**
   * Method; Deletes the frame.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [startFrameIndex] A zero-based integer index indicating the first frame to remove.
   * If omitted, the method uses the current selection; if there is no selection,
   * it removes all frames at the current playhead position on all layers.
   * @param [endFrameIndex] A zero-based integer index indicating the frame where removal stops (not inclusive).
   * If omitted, only the frame at **`startFrameIndex`** is removed.
   * @returns Nothing.
   * @example
   *
   * The following example deletes Frame 5 up to, but not including,
   * Frame 10 of the top layer in the current scene
   * (remember that index values are different from frame number values):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().currentLayer = 0;
   * fl.getDocumentDOM().getTimeline().removeFrames(4, 9);
   * ```
   *
   * The following example deletes Frame 8 on the top layer in the current scene:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().currentLayer = 0;
   * fl.getDocumentDOM().getTimeline().removeFrames(7);
   * ```
   */
  removeFrames(startFrameIndex?: number, endFrameIndex?: number): void;

  /**
   * Method; Removes the motion object and converts the frame(s) back to static frames.
   *
   * The parameters are optional,
   * and if specified set the timeline selection to the indicated frames prior to removing the motion object.
   * @since Adobe Flash Professional CS5
   * @param [startFrame] The first frame to start removing motion objects.
   * If omitted, the method uses the current selection;
   * if nothing is selected, it removes motion objects from all frames at the current playhead position on all layers.
   * @param [endFrame] The frame where removal stops; frames up to but not including **`endFrame`** are affected.
   * If omitted, only **`startFrame`** is used.
   * @returns Nothing.
   * @example
   *
   * The following example deletes all motion objects and converts the frames back to static frames
   * at the current playhead position on the top layer:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().currentLayer = 0;
   * fl.getDocumentDOM().getTimeline().removeMotionObject();
   * ```
   *
   * The following example deletes motion objects from Frame 5 up to, but not including,
   * Frame 15 of the top layer in the current scene:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().currentLayer = 0;
   * fl.getDocumentDOM().getTimeline().removeMotionObject(5, 15);
   * ```
   * @see {@link Timeline.createMotionObject | Timeline.createMotionObject()}
   */
  removeMotionObject(startFrame?: number, endFrame?: number): void;

  /**
   * Method; Moves the first specified layer before or after the second specified layer.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param layerToMove A zero-based index that specifies which layer to move.
   * @param layerToPutItBy A zero-based integer index indicating the layer to position the moved layer next to.
   * @param [addBefore] If `true` (default), moves the layer before **`layerToPutItBy`**; if `false`, moves it after.
   * @returns Nothing.
   * @example
   *
   * The following example moves the layer at index 2 to the top (on top of the layer at index 0):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().reorderLayer(2, 0);
   * ```
   *
   * The following example places the layer at index 3 after the layer at index 5:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().reorderLayer(3, 5, false);
   * ```
   */
  reorderLayer(layerToMove: number, layerToPutItBy: number, addBefore?: boolean): void;

  /**
   * Method; Reverses a range of frames.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [startFrameIndex] A zero-based integer index that specifies the first frame to start reversing.
   * If omitted, the current selection is used.
   * @param [endFrameIndex] A zero-based integer index specifying the frame at which to stop reversing.
   * The range includes frames from **`startFrameIndex`** up to, but not including, **`endFrameIndex`**.
   * If omitted, it defaults to **`startFrameIndex`**.
   * @returns Nothing.
   * @example
   *
   * The following example reverses the positions of the currently selected frames:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().reverseFrames();
   * ```
   *
   * The following example reverses frames from Frame 10 up to, but not including,
   * Frame 15 (remember that index values are different from frame number values):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().reverseFrames(9, 14);
   * ```
   */
  reverseFrames(startFrameIndex?: number, endFrameIndex?: number): void;

  /**
   * Method; Selects all the frames in the current timeline.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @returns Nothing.
   * @example
   *
   * The following example selects all the frames in the current timeline.
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().selectAllFrames();
   * ```
   */
  selectAllFrames(): void;

  /**
   * Method; Sets the property of the Frame object for the selected frames.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param property The name of the property to be modified.
   * For a complete list of properties and values, see the Property summary for the {@link Frame | Frame object}.
   *
   * You can't use this method to set values for read-only properties
   * such as {@link Frame.duration} and {@link Frame.elements}.
   * @param value The value to which you want to set the property.
   * To determine the appropriate values and type, see the {@link Frame | Frame object}.
   * @param [startFrameIndex] A zero-based integer index specifying the first frame to modify.
   * If omitted, the current selection is used.
   * @param [endFrameIndex] A zero-based integer index specifying the frame at which to stop (exclusive).
   * The range includes frames from **`startFrameIndex`** up to, but not including, **`endFrameIndex`**.
   * If omitted, it defaults to **`startFrameIndex`**.
   * @returns Nothing.
   * @example
   *
   * The following example assigns the ActionScript `stop()` command
   * to the first frame of the top layer in the current document:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().currentLayer = 0;
   * fl.getDocumentDOM().getTimeline().setSelectedFrames(0, 0, true);
   * fl.getDocumentDOM().getTimeline().setFrameProperty("actionScript", "stop();");
   * ```
   *
   * The following example sets a motion tween from Frame 2 up to, but not including,
   * Frame 5, of the current layer (remember that index values are different from frame number values):
   *
   * ```javascript
   * var doc = fl.getDocumentDOM();
   * doc.getTimeline().setFrameProperty("tweenType", "motion", 1, 4);
   * ```
   */
  setFrameProperty(property: string, value: any, startFrameIndex?: number, endFrameIndex?: number): void;

  /**
   * Method: Replaces the guide lines for the timeline
   * (`View > Guides > ShowGuides`) with the information specified in *xmlString*.
   *
   * To retrieve an XML string that can be passed to this method,
   * use {@link Timeline.getGuidelines | Timeline.getGuidelines()}.
   *
   * To view the newly set guide lines, you may have to hide them and then view them.
   * @since Adobe Flash Professional CS4
   * @param xmlString An XML string that contains information on the guidelines to apply.
   * @returns `true` if the guidelines are successfully applied; `false` otherwise.
   * @example
   *
   * The following example applies the guide lines from one FLA file to another FLA file:
   *
   * ```javascript
   * var doc0 = fl.documents[0];
   * var guides0 = doc0.timelines[0].getGuidelines();
   * var doc1 = fl.documents[1];
   * doc1.timelines[0].setGuidelines(guides0);
   * ```
   */
  setGuidelines(xmlString: string): boolean;

  /**
   * Method; Sets the specified property on all the selected layers to a specified value.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param property The property to set. For a list of properties, see {@link Layer | Layer object}.
   * @param value The value to which you want to set the property.
   * Use the same type of value you would use when setting the property in the layer object.
   * @param [layersToChange] A string that identifies which layers should be modified.
   *
   * Acceptable values are "selected", "all", and "others".
   * The default value is "selected".
   * @returns Nothing.
   * @example
   *
   * The following example makes the selected layer(s) invisible:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().setLayerProperty("visible", false);
   * ```
   *
   * The following example sets the name of the selected layer(s) to selLayer:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().setLayerProperty("name", "selLayer");
   * ```
   */
  setLayerProperty(property: string, value: any, layersToChange?: "selected" | "all" | "others"): void;

  /**
   * Method; Selects a range of frames in the current layer
   * or sets the selected frames to the selection array passed into this method.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param startFrameIndex A zero-based integer index that specifies the beginning frame to set.
   * @param endFrameIndex A zero-based integer index that specifies the end of the selection;
   * **`endFrameIndex`** is the frame after the last frame in the range to select.
   * @param [replaceCurrentSelection] A boolean value that,
   * if it is set to `true`, causes the currently selected frames to be deselected
   * before the specified frames are selected. The default value is `true`.
   * @returns Nothing.
   * @example
   *
   * The following examples show two ways to select the top layer, Frame 1, up to but not including Frame 10,
   * and then to add Frame 12 up to but not including Frame 15 on the same layer to the current selection
   * (remember that index values are different from frame number values):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().setSelectedFrames(0, 9);
   * fl.getDocumentDOM().getTimeline().setSelectedFrames(11, 14, false);
   * fl.getDocumentDOM().getTimeline().setSelectedFrames([0, 0, 9]);
   * fl.getDocumentDOM().getTimeline().setSelectedFrames([0, 11, 14], false);
   * ```
   *

   * @see {@link Timeline.getSelectedFrames | Timeline.getSelectedFrames()}
   */
  setSelectedFrames(startFrameIndex: number, endFrameIndex: number, replaceCurrentSelection?: boolean): void;

  /**
   * @overload
   * Method; Sets the selected frames to the selection array passed into this method.
   * @todo Supplement the example
   * @param selectionList An array of three integers,
   * as returned by {@link Timeline.getSelectedFrames | Timeline.getSelectedFrames()}.
   * @param [replaceCurrentSelection] A boolean value that,
   * if it is set to `true`, causes the currently selected frames to be deselected
   * before the specified frames are selected. The default value is `true`.
   * @example
   *
   * The following example first stores the array of selected frames in the `savedSelectionList` variable
   * and then uses the array later in the code to reselect those frames
   * after a command or user interaction has changed the selection:
   *
   * ```javascript
   * var savedSelectionList = fl.getDocumentDOM().getTimeline().getSelectedFrames();
   *
   * // Do something that changes the selection.
   *
   * fl.getDocumentDOM().getTimeline().setSelectedFrames(savedSelectionList);
   * ```
   */
  setSelectedFrames(selectionList: [number, number, number][], replaceCurrentSelection?: boolean): void;

  /**
   * Method; Sets the layer to be selected, and also makes the specified layer the current layer.
   *
   * Selecting a layer also means that all the frames in the layer are selected.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param index A zero-based integer index for the layer to select.
   * @param [replaceCurrentSelection] A boolean value that,
   * if it is set to `true`, causes the method to replace the current selection;
   * `false` causes the method to extend the current selection. The default value is `true`.
   * @returns Nothing.
   * @usage Timeline.setSelectedLayers(index [, replaceCurrentSelection])
   * @example
   *
   * The following example selects the top layer:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().setSelectedLayers(0);
   * ```
   *
   * The following example adds the next layer to the selection:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().setSelectedLayers(1, false);
   * ```
   * @see {@link Timeline.getSelectedLayers | Timeline.getSelectedLayers()}
   */
  setSelectedLayers(index: number, replaceCurrentSelection?: boolean): void;

  /**
   * Method; Shows the layer masking during authoring by locking the mask and masked layers.
   *
   * This method uses the current layer if no layer is specified.
   *
   * If you use this method on a layer that is **not** of type **Mask** or **Masked**,
   * Animate displays an error in the Output panel.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @param [layer] A zero-based integer index of a mask or masked layer to show masking during authoring.
   * @returns Nothing.
   * @example
   *
   * The following example specifies that the layer masking of the first layer should show during authoring.
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().showLayerMasking(0);
   * ```
   */
  showLayerMasking(layer?: number): void;

  /**
   * Method; Starts automatic playback of the timeline if it is currently playing.
   *
   * This method can be used with SWF panels to control timeline playback in the authoring environment.
   * @since Adobe Flash Professional CS5
   * @returns Nothing.
   * @example
   *
   * The following example starts playback of the timeline.
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().startPlayback();
   * ```
   */
  startPlayback(): void;

  /**
   * Method; Stops automatic playback of the timeline if it is currently playing.
   *
   * This method can be used with SWF panels to control timeline playback in the authoring environment.
   * @since Adobe Flash Professional CS5
   * @returns Nothing.
   * @example
   *
   * The following example stops playback of the timeline.
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().stopPlayback();
   * ```
   */
  stopPlayback(): void;

  /**
   * Property; A boolean value that specifies the advanced layers mode is enabled or disabled.
   * @since Adobe Animate 2020
   * @example
   *
   * The following example enables the advanced layers mode.
   *
   * ```javascript
   * var timeline = an.getDocumentDOM().getTimeline();
   * timeline.advancedLayersEnabled = true;
   * ```
   */
  advancedLayersEnabled: boolean;

  /**
   * Property; The zero-based index for the frame at the current playhead location.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @example
   *
   * The following example sets the playhead of the current timeline to Frame 10
   * (remember that index values are different from frame number values):
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().currentFrame = 9;
   * ```
   *
   * The following example stores the value of the current playhead location in the curFrame variable:
   *
   * ```javascript
   * var curFrame = fl.getDocumentDOM().getTimeline().currentFrame;
   * ```
   */
  currentFrame: number;

  /**
   * Property; The zero-based index for the currently active layer.
   *
   * A value of 0 specifies the top layer, a value of 1 specifies the layer below it, and so on.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @example
   *
   * The following example makes the top layer active:
   *
   * ```javascript
   * fl.getDocumentDOM().getTimeline().currentLayer = 0;
   * ```
   *
   * The following example stores the index of the currently active layer in the curLayer variable:
   *
   * ```javascript
   * var curLayer = fl.getDocumentDOM().getTimeline().currentLayer;
   * ```
   */
  currentLayer: number;

  /**
   * Read-only property; An integer that represents the number of frames in this timeline's longest layer.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @example
   *
   * The following example uses a `countNum` variable
   * to store the number of frames in the current document's longest layer:
   *
   * ```javascript
   * var countNum = fl.getDocumentDOM().getTimeline().frameCount;
   * ```
   */
  readonly frameCount: number;

  /**
   * Read-only property; The number of layers in the specified timeline.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @example
   *
   * The following example uses the NumLayer variable to store the number of layers in the current scene:
   *
   * ```javascript
   * var NumLayer = fl.getDocumentDOM().getTimeline().layerCount;
   * ```
   */
  readonly layerCount: number;

  /**
   * Read-only property; An array of layer objects.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @example
   *
   * The following example uses the `currentLayers` variable
   * to store the array of layer objects in the current document:
   *
   * ```javascript
   * var currentLayers = fl.getDocumentDOM().getTimeline().layers;
   * ```
   */
  readonly layers: Layer[];

  /**
   * Read-only property; If the timeline's `libraryItem` property is `null`, the timeline belongs to a scene.
   * If it's not `null`, you can treat it like a Library {@link Item | Item object}.
   * @since Adobe Flash Professional CS5
   * @example
   *
   * The following example outputs the name of the `libraryItem` if the value of libraryItem is not `null`,
   * and the name of the scene if `librayItem` is `null`:
   *
   * ```javascript
   * var item = fl.getDocumentDOM().getTimeline().libraryItem;
   * if (item) fl.trace("libraryItem name: " + item.name);
   * else fl.trace("scene name: " + fl.getDocumentDOM().getTimeline().name);
   * ```
   */
  readonly libraryItem: Item | null;

  /**
   * Property; The name of the current timeline.
   *
   * This name is the name of the current scene, screen (slide or form), or symbol that is being edited.
   * @since Macromedia Flash MX Basic/Professional 2004
   * @example
   *
   * The following example retrieves the first scene name:
   *
   * ```javascript
   * var sceneName = fl.getDocumentDOM().timelines[0].name;
   * ```
   *
   * The following example sets the first scene name to "FirstScene":
   *
   * ```javascript
   * fl.getDocumentDOM().timelines[0].name = "FirstScene";
   * ```
   */
  name: string;
}
